"""add job embedding field

Revision ID: 5ca8d0c895c4
Revises: a16afe4cec7d
Create Date: 2026-04-06 11:44:22.020206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca8d0c895c4'
down_revision: Union[str, Sequence[str], None] = 'a16afe4cec7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('embedding_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'embedding_json')
    # ### end Alembic commands ###
